version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    restart: always
